[project]
name = "gatherpass_api_client"
version = "0.1.0"
dependencies = [
    "httpx",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# --- ADD THIS SECTION ---
[tool.setuptools.packages.find]
where = ["src"]
